### ISSUE TITLE
ImportError: No module named storage.blob.baseblobservice

### ISSUE THREAD

**Issue by colemickens** [SUSE/azurectl#187]
```
ERROR: Unexpected error:
Traceback (most recent call last):
  File "/usr/bin/azurectl", line 9, in <module>
    load_entry_point('azurectl==2.1.1', 'console_scripts', 'azurectl')()
  File "/usr/lib/python2.7/site-packages/azurectl-2.1.1-py2.7.egg/azurectl/azurectl.py", line 45, in main
    App()
  File "/usr/lib/python2.7/site-packages/azurectl-2.1.1-py2.7.egg/azurectl/app.py", line 26, in __init__
    app = CliTask()
  File "/usr/lib/python2.7/site-packages/azurectl-2.1.1-py2.7.egg/azurectl/commands/base.py", line 46, in __init__
    self.task = self.cli.load_command()
  File "/usr/lib/python2.7/site-packages/azurectl-2.1.1-py2.7.egg/azurectl/cli.py", line 151, in load_command
    'azurectl.commands.' + service + '_' + command
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/azurectl-2.1.1-py2.7.egg/azurectl/commands/setup_account.py", line 90, in <module>
    from ..storage.container import Container
  File "/usr/lib/python2.7/site-packages/azurectl-2.1.1-py2.7.egg/azurectl/storage/container.py", line 14, in <module>
    from azure.storage.blob.baseblobservice import BaseBlobService
ImportError: No module named storage.blob.baseblobservice
```

Not sure what I'm doing wrong here.

**Comment by schaefi** [comment]
your Azure SDK installation seems missing/incomplete/outdated

How did you prepare the environment ?

imho an easy way to ensure all required python stuff gets installed would be to just install the rpm packages with zypper from here

http://download.opensuse.org/repositories/Cloud:/Tools/

Alternatively you can setup a python virtual env as described here:

https://github.com/SUSE/azurectl/#contributing

Let me know if that helped

**Comment by colemickens** [comment]
It seems like it has to do with how azure-storage is built. Apparently using `pip install .` instead of `python setup.py install` was sufficient to fix this issue, though I don't really understand what's at play there. Anyway, I think this is resolved for now. Thanks.
