### ISSUE TITLE
What format is the PEM supposed to be in?

### ISSUE THREAD

**Issue by colemickens** [SUSE/azurectl#188]
What PKSC flavor is it meant to be in?

I've tried a PFX, I've tried a PEM of the private key and a PEM of the cert. They all wind up throwing an error:

```shell
root@cmz420:/opt/cole# azurectl compute vm regions
ERROR: Unexpected error:
Traceback (most recent call last):
  File "/usr/local/bin/azurectl", line 11, in <module>
    load_entry_point('azurectl==2.1.1', 'console_scripts', 'azurectl')()
  File "/usr/local/lib/python2.7/dist-packages/azurectl/azurectl.py", line 45, in main
    App()
  File "/usr/local/lib/python2.7/dist-packages/azurectl/app.py", line 31, in __init__
    task_class().process()
  File "/usr/local/lib/python2.7/dist-packages/azurectl/commands/compute_vm.py", line 135, in process
    self.__list_locations()
  File "/usr/local/lib/python2.7/dist-packages/azurectl/commands/compute_vm.py", line 165, in __list_locations
    self.result.add('regions', self.account.locations('PersistentVMRole'))
  File "/usr/local/lib/python2.7/dist-packages/azurectl/account/service.py", line 130, in locations
    for location in service.list_locations():
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementservice.py", line 1131, in list_locations
    Locations)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementclient.py", line 365, in _perform_get
    response = self.perform_get(path, x_ms_version)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementclient.py", line 175, in perform_get
    response = self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementclient.py", line 337, in _perform_request
    resp = self._filter(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/_http/httpclient.py", line 183, in perform_request
    self.send_request_body(connection, request.body)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/_http/httpclient.py", line 142, in send_request_body
    connection.send(None)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/_http/requestsclient.py", line 81, in send
    self.response = self.session.request(self.method, self.uri, data=request_body, headers=self.headers, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL] PEM lib (_ssl.c:2603)
```

**Comment by colemickens** [comment]
I expected, for example, to have to specify a client cert and the client private key...

**Comment by colemickens** [comment]
`openssl pkcs12 -in file.pfx -out file.pem -nodes` did the trick, now I get an auth error but I assume that's a different issue.
